In [2]:
import tensorflow as tf
import numpy as np

In [6]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/kaswani/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [9]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324.4, tf.int16)
floating  = tf.Variable(3.567,tf.float64)

In [13]:
string = tf.Variable(["new","hello"],tf.string)

In [14]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [17]:
n_dim = tf.Variable([[1,2],[3,4]], tf.float64)

In [18]:
tf.rank(n_dim)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [20]:
string.shape

TensorShape([2])

#### Changing shape

In [29]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3,-1])

In [30]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
